export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT = "LOGOUT"

// export const RESET_FORM = "RESET_FORM"

//Users Attributes
export const REQUEST_NOTEBOOKS= "RREQUEST_NOTEBOOKS"
export const ADD_NOTEBOOK = "ADD_NOTEBOOK"
export const UPDATE_NOTEBOOK = "UPDATE_NOTEBOOK"
export const DELETE_NOTEBOOK = "DELETE_NOTEBOOK"

